### PR TITLE
Minor documentation fixes

### PR DESCRIPTION
**Pull request by moleculezz**
I finished reading the guide and thought I'd submit a PR with some minor issues I came across.

### CODE REVIEW

**Comment by evancz** [comment]
Can you split this into separate pull requests? Each of these commits should be their own PR. For example, I do not want to do the comma one. Always following the rules is boring.

**Comment by moleculezz** [comment]
Ok.. I can do a revert on that specific commit. Would that be OK or do you still prefer a separate commit for each?

**Comment by evancz** [comment]
You can revert the comma one and change the link from `types/union_types.md` to `../types/union_types.md` and it should be fine.

Separate PRs is definitely preferred though!

**Comment by moleculezz** [comment]
I will make sure to separate PR's in the future.

**Comment by evancz** [comment]
Thanks!

**Pull request merged**
