### PR TITLE
Update forms.md

### PR DESCRIPTION
**Pull request by iammerrick**
Fix Typo

### CODE REVIEW

**Comment by gampleman** [comment]
Why do you think this isa typo?

**Comment by iammerrick** [comment]
For some reason I thought msg was the type Msg. (Much like view's type in this context).

In the syntax:

```elm
viewValidation : Model -> Html Msg
viewValidation model =
     ..
```

The `Html Msg` part, in the guides I understood that to mean. "Takes a Model and returns Html that produces Msg's". Is there a better way to understand that type signature?

**Comment by gampleman** [comment]
The lowercase msg is a type variable that can represent any type. This makes the function generic - you can use it in any part of the app regardless of what the Msg type you are using is.

**Comment by iammerrick** [comment]
Got it! Thank you @gampleman

**Comment by ahstro** [comment]
I found this very confusing as well, especially since I didn't get an error in either case. Maybe some clarifiaction in the guide could be useful?

**Comment by toraritte** [comment]
I agree with @ahstro . I had some Haskell exposure so it is clear that `msg` here is a polymorphic type variable, but why not use the more concrete `Msg` type here instead? It wouldn't raise any questions for newcomers (it would get explained in the chapter on types) and it (at least here) validates the `Msg` type inputs.

**Pull request closed without merging**
